// Stub implementation for @dropiti/sdk/enums
export enum RealEstateOfferStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  COUNTERED = 'COUNTERED',
  WITHDRAWN = 'WITHDRAWN',
  CANCELLED = 'CANCELLED'
}

export enum RealEstateOfferAction {
  INITIATOR_CREATED = 'INITIATOR_CREATED',
  INITIATOR_ACCEPTED = 'INITIATOR_ACCEPTED',
  INITIATOR_REJECTED = 'INITIATOR_REJECTED',
  INITIATOR_COUNTERED = 'INITIATOR_COUNTERED',
  INITIATOR_WITHDRAWN = 'INITIATOR_WITHDRAWN',
  INITIATOR_CANCELLED = 'INITIATOR_CANCELLED',
  INITIATOR_EDITED = 'INITIATOR_EDITED',
  RECIPIENT_CREATED = 'RECIPIENT_CREATED',
  RECIPIENT_ACCEPTED = 'RECIPIENT_ACCEPTED',
  RECIPIENT_REJECTED = 'RECIPIENT_REJECTED',
  RECIPIENT_COUNTERED = 'RECIPIENT_COUNTERED',
  RECIPIENT_WITHDRAWN = 'RECIPIENT_WITHDRAWN',
  RECIPIENT_CANCELLED = 'RECIPIENT_CANCELLED',
  RECIPIENT_EDITED = 'RECIPIENT_EDITED'
}
